import { useState,useEffect,useMemo } from "react";
import {ColorModeContext,useMode} from "./theme"
import {ThemeProvider} from "@mui/material"
import Topbar from "./scenes/global/Topbar";
import CssBaseline from '@mui/material/CssBaseline';
import { Route, Routes } from "react-router-dom";
import { Dashboard } from "@mui/icons-material";
import Bar from "./scenes/bar";
import Line from "./scenes/line"
import Invocation from "./scenes/invocations/Invocation";
import UserGraphs from "./scenes/graphs/Usergraphs";
import GraphComponent from "./scenes/graphs/Refgraph";
import GraphVisualization from "./scenes/graphs/Refgraph";

var data = {
  Nodes: [
    {
      NodeId: "fm9m",
      NodeName: "Resize",
      Path: "examples/image-processing-diamond-multicloud-aws-to-az/src/Resize",
      EntryPoint: "func.py",
      MemoryInMB: 512,
      IsFused: true,
      IsAutoGenerated: false,
    },
    {
      NodeId: "b74b",
      NodeName: "Mobilenet",
      Path: "examples/image-processing-diamond-multicloud-aws-to-az/src/Mobilenet",
      EntryPoint: "func.py",
      MemoryInMB: 512,
      IsFused: true,
      IsAutoGenerated: false,
    },
    // Other nodes
  ],
  Edges: [
    {
      fm9m: ["b74b"],
    },
    // Other edges
  ],
  wf_partitions: [
    {
      partition_label: "label for datacentre",
      func_ids: ["fm9m", "b74b"],
    },
  ],
  wf_fusion_config: [
    {
      fused_func_id: "fm9m_b74b",
      original_func_ids: ["fm9m", "b74b"],
    },
  ],
};






function App() {
const [theme,colorMode]=useMode();
  return (
    <ColorModeContext.Provider value={colorMode}>
      <ThemeProvider theme={theme}>
        <CssBaseline />
            <div className="app"> 
              <main className="context">
                <Topbar />

             
              
        <Routes>
          {/* <Route path="/" element={}/> */}
            
           <Route path="/" element={<Bar/>}/>
        

        </Routes>
           
              </main>
              </div>

        </ThemeProvider>
      </ColorModeContext.Provider>
  
  
  );
}

export default App;
